import { SERVICES_MODULES } from './modules.cofig'

const BASE_PATHS = {
  AUTH: 'accounts/',
  ACCOUNTS: 'accounts/',
  PERSON: 'person/',
  CORE: 'core/',
  ADMISSION: 'admission/',
  PROGRAM: 'program/',
  FILE: 'manager/',
  REPORT: 'report/',
  EVALUATION: 'evaluation/',
  ACADEMIC: 'academic/',
  ECONOMIC: 'economic/',
}

const MODELS_PATHS = {
  USER: 'users/',
  PERSON: 'person/',
}

export const ENDPOINTS_CONFIG = {
  AUTH: {
    LOGIN: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}login/`,
    EMAIL_ACCESS_CODE: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}email-code/`,
    VERIFY_ACCESS_CODE: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}verify-code/`,
    RECOVERY_PASSWORD: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}recovery-password/`,
    EMAIL_APPLICANT: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}email-applicant/`,
    REFRESH_SESSION: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}refresh-session/`,
    LOGIN_WITH_GOOGLE: `${BASE_PATHS.AUTH}${MODELS_PATHS.USER}google_sign_in/`,
  },
  ACCOUNTS: {
    ACCESS_MENU: `${BASE_PATHS.ACCOUNTS}user/accessmenu/`,
    CREATE_ACCOUNT: `${BASE_PATHS.ACCOUNTS}user/create-account/`,
    CHANGE_PASSWORD: `${BASE_PATHS.ACCOUNTS}user/change-password/`,
    EMAIL_CHANGE: `${BASE_PATHS.ACCOUNTS}user/email-change/`,
    MENU: `${BASE_PATHS.ACCOUNTS}user/access_menu/`,
  },
  PERSON: {
    DOCUMENT_TYPE: `${BASE_PATHS.PERSON}documenttype/`,
    PERSON: `${BASE_PATHS.PERSON}${MODELS_PATHS.PERSON}`,
    PERSON_TYPE: `${BASE_PATHS.PERSON}persontype/`,
    MARITAL_STATUS: `${BASE_PATHS.PERSON}maritalstatus/`,
    ACADEMIC_DEGREE: `${BASE_PATHS.PERSON}academicdegree/`,
    JOB_SECTOR: `${BASE_PATHS.PERSON}jobsector/`,
    ACADEMIC_INFO: `${BASE_PATHS.PERSON}academicinfo/`,
    ACADEMIC_INFO_LIST: `${BASE_PATHS.PERSON}academicinfo/get_academic_info/`,
    LANGUAGE_INFO: `${BASE_PATHS.PERSON}idiominfo/`,
    JOB_INFO: `${BASE_PATHS.PERSON}jobinfo/`,
    JOB_INFO_LIST: `${BASE_PATHS.PERSON}jobinfo/get_job_info/`,
    PERSON_INFO: `${BASE_PATHS.PERSON}contactinfo/`,
    PROGRESS_INFO: `${BASE_PATHS.PERSON}person/progress_info/`,
    PERSON_FILES: `${BASE_PATHS.PERSON}files/`,
    PERSON_FILES_PENDING: `${BASE_PATHS.PERSON}person/files_requirements/`,
    GET_PERSON_USER: `${BASE_PATHS.PERSON}person/get_person/`,
    UPDATE_PHOTO: `${BASE_PATHS.PERSON}person/update_photo/`,
    PERSON_APPLICANT: `${BASE_PATHS.PERSON}person/person-applicant/`,
  },
  CORE: {
    ADMIN_UNITY: `${BASE_PATHS.CORE}adminunity/`,
    RECTORAL_RESOLUTION: `${BASE_PATHS.CORE}rectoralresolution/`,
    DIRECTORAL_RESOLUTION: `${BASE_PATHS.CORE}directoralresolution/`,
    STAFF_TYPE: `${BASE_PATHS.CORE}stafftype/`,
    STAFF: `${BASE_PATHS.CORE}staff/`,
    COUNTRY: `${BASE_PATHS.CORE}country/`,
    UBIGEO: `${BASE_PATHS.CORE}ubigeo/`,
    HEADQUARTER: `${BASE_PATHS.CORE}headquarter/`,
    OCCUPATION: `${BASE_PATHS.CORE}occupation/`,
    ADMIN_JOB_OCCUPATION: `${BASE_PATHS.CORE}adminjoboccupation/`,
    PERIOD: `${BASE_PATHS.CORE}period/`,
    ACTION_TYPE: `${BASE_PATHS.CORE}actiontype/`,
    STUDENT_FILE_HISTORY: `${BASE_PATHS.CORE}studentfilehistory/`,
    UBIGEO_FILTERDATA: `${BASE_PATHS.CORE}ubigeo/filterdata/`,
    COUNTRY_FILTERDATA: `${BASE_PATHS.CORE}country/filterdata/`,
    FACULTY: `${BASE_PATHS.CORE}adminunity/`,
    UNIVERSITY: `${BASE_PATHS.CORE}university/`,
    PROFESIONAL_SCHOOL: `${BASE_PATHS.CORE}school/`,
  },
  ADMISSION: {
    DISPONIBILITY_ENROLLMENT: `${BASE_PATHS.ADMISSION}enrollmentstage/active-enrollment-stage/`,
  },
  ACADEMIC: {
    ENROLLMENT: `${BASE_PATHS.ACADEMIC}enrollment/`,
    ENROLLMENT_STAGE: `${BASE_PATHS.ACADEMIC}enrollmentstage/`,
    ENROLLMENT_STAGE_PERSON: `${BASE_PATHS.ACADEMIC}enrollmentstage/active-enrollment-stage/`,
    ENROLLMENT_VALIDATE: `${BASE_PATHS.ACADEMIC}enrollment/validate-enrollment/`,
    COURSE_GROUP: `${BASE_PATHS.ACADEMIC}coursegroup/course-group-enrollment-list/`,
    ENROLLMENT_CREATE: `${BASE_PATHS.ACADEMIC}enrollment/create-enrollment/`,
    DETAILS_STUDENT_FILE: `${BASE_PATHS.ACADEMIC}studentfile/student-file-details/`,
    DETAILS_ENROLLMENT: `${BASE_PATHS.ACADEMIC}enrollment/enrollment-details/`,
    STUDENT_FILE_PROGRAMS: `${BASE_PATHS.ACADEMIC}studentfile/student-file-programs/`,
    ENROLLMENT_LIST: `${BASE_PATHS.ACADEMIC}enrollment/enrollment-list/`,
  },
  PROGRAM: {
    INFO_STUDY_PLAN: `${BASE_PATHS.PROGRAM}study-plan/studyplan_info/`,
    PROGRAM: `${BASE_PATHS.PROGRAM}program/`,
    PROGRAM_TYPE: `${BASE_PATHS.PROGRAM}program-type/`,
    STUDY_PLAN: `${BASE_PATHS.PROGRAM}study-plan/`,
    COURSE: `${BASE_PATHS.PROGRAM}course/`,
    COURSE_REQUIREMENT: `${BASE_PATHS.PROGRAM}course-requirement/`,
    KNOWLEDGE_AREA: `${BASE_PATHS.PROGRAM}knowledge-area/`,
    PROGRAM_STUDY_PLAN: `${BASE_PATHS.PROGRAM}program/programs_study_plan/`,
  },
  FILE: {
    FILE_TYPES: `${BASE_PATHS.FILE}filetypes/`,
    REQUIREMENT_FILES: `${BASE_PATHS.FILE}requirementfiles/`,
    FILES: `${BASE_PATHS.FILE}files/`,
    PERSON_FILES_PENDING: `${BASE_PATHS.FILE}files/person_files_requirements/`,
  },
  REPORT: {
    GET_CV_PERSON: `${BASE_PATHS.REPORT}hoja-vida/`,
    GET_APPLICATION_HISTORY: `${BASE_PATHS.REPORT}application-history`,
    GET_PERSON_REPORT: `${BASE_PATHS.REPORT}persons-report/`,
    EVALUATION_PDF: (convocatory_token: string, aplicant_id: string) =>
      `${SERVICES_MODULES.REPORT.URL_PROD}${BASE_PATHS.REPORT}seat-aplicant-report/?convocatory=${convocatory_token}&applicant=${aplicant_id}`,
    ACTA_EVALUATION_AULA: (convocatory_token: string, aula_id: string) =>
      `${SERVICES_MODULES.REPORT.URL_PROD}${BASE_PATHS.REPORT}classroom-evaluation-report/?convocatory_token=${convocatory_token}&classroom_id=${aula_id}`,
  },
  BULKS: {
    EVENT_CALL_BULK: `${BASE_PATHS.ADMISSION}bulks/timelinebulk/`,
  },
  ADMIN: {
    CONVOCATORY_SUMMARY: `${BASE_PATHS.ADMISSION}convocatory/convocatory_summary/`,
    DISTRIBUTION_PROGRAM: `${BASE_PATHS.ADMISSION}convocatory/distribution_by_program/`,
    LAST_INROLLEMENT: `${BASE_PATHS.ADMISSION}applicantfile/applicants_convocatory/`,
    PROGRAM_FILTER: `${BASE_PATHS.ADMISSION}convocatory/program_filter/`,
  },
  EVALUATION: {
    EVALUATION: `${BASE_PATHS.EVALUATION}evaluation/`,
    DIMENSION: `${BASE_PATHS.EVALUATION}dimension/`,
    CRITERION: `${BASE_PATHS.EVALUATION}criterion/`,
    EVALUATION_RESULT: `${BASE_PATHS.EVALUATION}evaluation_result/`,
    EVALUATION_DIMENSION_BY_CRITERION: `${BASE_PATHS.EVALUATION}dimension/dimension_by_criterion/`,
    USERS_EVALUATION: `${BASE_PATHS.ACCOUNTS}user/user-admin-list/`,
    DIMENSION_BY_EXTERNAL: `${BASE_PATHS.EVALUATION}dimension/dimension_by_external/`,
    EVALUATION_FORM: `${BASE_PATHS.EVALUATION}bulks/evaluation_result_bulk/`,
  },
  PAYMENT: {
    PAYMENT: `${BASE_PATHS.ECONOMIC}payment/`,
    CONCEPT: `${BASE_PATHS.ECONOMIC}concept/`,
  },
  DOWNLOAD: {
    DOWNLOAD_CERTIFICATE: `${BASE_PATHS.REPORT}registration-certificate-report/`,
  },
}
